// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proxy.proto

#include "proxy.pb.h"
#include "proxy.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace proxy {

static const char* Proxy_method_names[] = {
  "/proxy.Proxy/NotifyUser",
};

std::unique_ptr< Proxy::Stub> Proxy::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Proxy::Stub> stub(new Proxy::Stub(channel, options));
  return stub;
}

Proxy::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_NotifyUser_(Proxy_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Proxy::Stub::NotifyUser(::grpc::ClientContext* context, const ::common::Request& request, ::common::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::common::Request, ::common::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NotifyUser_, context, request, response);
}

void Proxy::Stub::experimental_async::NotifyUser(::grpc::ClientContext* context, const ::common::Request* request, ::common::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::common::Request, ::common::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NotifyUser_, context, request, response, std::move(f));
}

void Proxy::Stub::experimental_async::NotifyUser(::grpc::ClientContext* context, const ::common::Request* request, ::common::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NotifyUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::common::Response>* Proxy::Stub::PrepareAsyncNotifyUserRaw(::grpc::ClientContext* context, const ::common::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::common::Response, ::common::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NotifyUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::common::Response>* Proxy::Stub::AsyncNotifyUserRaw(::grpc::ClientContext* context, const ::common::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNotifyUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

Proxy::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Proxy_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Proxy::Service, ::common::Request, ::common::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Proxy::Service* service,
             ::grpc::ServerContext* ctx,
             const ::common::Request* req,
             ::common::Response* resp) {
               return service->NotifyUser(ctx, req, resp);
             }, this)));
}

Proxy::Service::~Service() {
}

::grpc::Status Proxy::Service::NotifyUser(::grpc::ServerContext* context, const ::common::Request* request, ::common::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proxy

